[package]
name = "lazy_phonememize"
version = "0.1.1-rc"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
libc = "0.2.169"
regex = "1.11.1"

[dev-dependencies]
clap = { version = "4.5.28", features = ["derive"] }

[profile.release]
opt-level = "z"
strip = true  # WE STRIPPING THE SYMBOLS WITH THIS ONE  ğŸ—£ï¸ğŸ—£ï¸ğŸ”¥ğŸ”¥ğŸ”¥
lto = true

